baseURL: "https://jettchen.me/"
languageCode: en-us
title: Jett Chen
theme: PaperMod
params:
  env: production
  description: "Jett Chen's personal website"
  images:
    - https://avatars.githubusercontent.com/u/45888395?v=4
  defaultTheme: auto
  profileMode:
    enabled: true
    title: "Jett Chen" # optional default will be site title
    subtitle: "I like building and breaking software. Exploring Cybersecurity, AI, and Systems." # optional default will be site subtitle
    imageUrl: "https://avatars.githubusercontent.com/u/45888395?v=4" # optional
    imageTitle: "My avatar" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: "Read my Blog"
        url: "https://blog.jettchen.me"
  socialIcons:
    - name: github
      url: "https://github.com/JettChenT"
    - name: twitter
      url: "https://twitter.com/JettChen5"
    - name: email
      url: "mailto:contact@jettchen.me"
